/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{js,jsx,ts,tsx}"],
  theme: {
    extend: {
      colors: {
        ghostwhite: "#f7f6fe",
        white: "#fff",
        darkslategray: {
          "100": "#393e46",
          "200": "#333",
        },
        darkorchid: "#6829b3",
        midnightblue: {
          "100": "#151965",
          "200": "#00005c",
        },
        black: "#000",
        goldenrod: "#ffb347",
        "colors-basic-color-1": "#12022f",
        sandybrown: "#d6a85a",
        "colors-basic-color-2": "#594d6d",
        lightskyblue: "#92bdff",
        gainsboro: "#d9d9d9",
        red: "#ec1515",
        lime: "#42f615",
        dimgray: "#5f5a5a",
        whitesmoke: "#ebecee",
        darkgray: "#b4a3a3",
        "colors-action-color-1": "#ffdda9",
        antiquewhite: "#ddd1c0",
      },
      fontFamily: {
        catamaran: "Catamaran",
        montserrat: "Montserrat",
        "display-03": "'DM Sans'",
        "abyssinica-sil": "'Abyssinica SIL'",
        inherit: "inherit",
      },
      borderRadius: {
        "31xl": "50px",
        "11xl": "30px",
        lg: "18px",
        "61xl": "80px",
        xl: "20px",
        "3xs": "10px",
      },
    },
    fontSize: {
      base: "1rem",
      "3xl": "1.38rem",
      "5xl": "1.5rem",
      mini: "0.94rem",
      mid: "1.06rem",
      "6xl": "1.56rem",
      "29xl": "3rem",
      "31xl": "3.13rem",
      lg: "1.13rem",
      "9xl": "1.75rem",
      "37xl": "3.5rem",
      "26xl": "2.81rem",
      sm: "0.88rem",
      xs: "0.75rem",
      xl: "1.25rem",
    },
  },
  corePlugins: {
    preflight: false,
  },
};
